# Select image from https://hub.docker.com/r/_/php/
image: php:5.6

before_script:
# Install dependencies
- bash ci/docker_install.sh > /dev/null

test:app:
  script:
  - phpunit --configuration phpunit_myapp.xml
  
# We test PHP7.0 (good luck with that)
test:7.0:
  image: php:7.0
  script:
  - phpunit --configuration phpunit_myapp.xml
  
  before_script:
- cp my_php.ini /usr/local/etc/php/conf.d/test.ini

test:app:
  script:
  - phpunit --configuration phpunit_myapp.xml
